EBBS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auth_.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('board/', include('board.urls')),
    path('chat/', include('chat.urls')),
]

auth_/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'Auth_'
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('logout/', views.out, name='logout'),
]

board/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'Board'
urlpatterns = [
    path('', views.Board, name='board'),
    path('<int:pk>', views.threadview, name='thread'),
    path('<int:pk>/delete/', views.ThreadDelete.as_view(), name='delete_thread'),

]

chat/urls.py
from django.urls import path
from . import views

app_name = 'Chat'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

board/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User

users = len(User.objects.all())


class Thread(models.Model):
    def __str__(self):
        return self.thread_title

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    thread_title = models.CharField(max_length=100)
    thread_text = models.CharField(max_length=5000)
    pub_date = models.DateTimeField('Date published', auto_now=True)
    CATEGORY_CHOICES = [('Random', 'Random'), ('Broadcast', 'Broadcast'), ('Animation', 'Animation'), ('Artwork', 'Artwork'), ('Cinematics', 'Cinematics'), ('Videogames', 'Videogames')]
    category = models.CharField(max_length=100, choices=CATEGORY_CHOICES)
    thread_author = models.CharField(max_length=200)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Comment(models.Model):
    def __str__(self):
        return self.comment_text

    def was_published(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    comment_text = models.CharField(max_length=2500)
    comment_post = models.ForeignKey(Thread, related_name='thread_id', on_delete=models.CASCADE)
    comment_author = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Date published', null=True, blank=True, auto_now=True)

# Create your models here.

chat/models.py
from django.db import models

# Create your models here.

board/forms.py
from django import forms
from .models import Thread, Comment


class CreateThread(forms.Form):
    thread_title = forms.CharField(label='Thread title', max_length=100)
    thread_text = forms.CharField(label='Thread text', max_length='1500', widget=forms.Textarea)
    choises = [('Random', 'Random'), ('Broadcast', 'Broadcast'), ('Animation', 'Animation'),
               ('Artwork', 'Artwork'), ('Cinematics', 'Cinematics'), ('Videogames', 'Videogames')]
    topic = forms.ChoiceField(choices=choises)


class ThreadForm(forms.ModelForm):

    thread_title = forms.CharField(label=False, max_length=100, widget=forms.TextInput(attrs={'style': 'background: #454545; color: #f9f9f9;', 'placeholder': 'Thread title'}))
    thread_text = forms.CharField(label=False, max_length='1500', widget=forms.Textarea(attrs={'style': 'background: #454545; color: #f9f9f9;', 'rows': '2.5', 'placeholder': 'Thread text'}),)
    choises = [('Random', 'Random'), ('Broadcast', 'Broadcast'), ('Animation', 'Animation'), ('Artwork', 'Artwork'),
               ('Cinematics', 'Cinematics'), ('Videogames', 'Videogames')]
    category = forms.ChoiceField(label=False, choices=choises, widget=forms.Select(attrs={'style':'background: #454545; color: #f9f9f9'}))

    class Meta:
        model = Thread
        fields = ('thread_title', 'thread_text', 'category')


class CommentForm(forms.ModelForm):

    comment_text = forms.CharField(label=False, max_length=1500, widget=forms.Textarea(attrs={'style':'background: #454545; color: #f9f9f9;', 'rows':'2.5', 'placeholder':'Start typing your comment here', }))


    class Meta:
        model = Comment
        fields = ('comment_text',)

auth_/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout


def index(request):
    return render(request, 'index.html')


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('Auth_:index')
    else:
        form = UserCreationForm()
    context = {'form': form}
    return render(request, 'registration/register.html', context)


def out(request):
    logout(request)
    return redirect('Auth_:index')

board/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.template import loader
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView
from .models import Thread, Comment
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .forms import ThreadForm, CommentForm


def main(request):
    return render(request, 'main.html')


@method_decorator(login_required, name='dispatch')
class CommentsView(generic.DetailView):
    model = Comment
    template_name = 'board/comments.html'


@login_required
def Board(request):
    #thread = get_object_or_404(Thread)
    latest_thread = Thread.objects.order_by('-pub_date')[:10]
    template = loader.get_template('board/board.html')

    if request.method == 'POST':
        form = ThreadForm(request.POST)
        if form.is_valid():
            former = form.save(commit=False)
            former.category = form.cleaned_data['category']
            former.thread_author = request.user
            former.save()
            return HttpResponseRedirect(reverse('Board:board'))
        else:
            raise Http404("Something went wrong")
    form = ThreadForm()
    context = {
        'latest_threads': latest_thread,
        'form': form,
    }
    return HttpResponse(template.render(context,request))



class ThreadDelete(DeleteView):
    model = Thread
    success_url = reverse_lazy('Board:board')


@login_required
def threadview(request, pk):
    thread = Thread.objects.get(id = pk)
    comments = Comment.objects.filter(comment_post = thread)
    template = loader.get_template('board/thread.html')

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            former = form.save(commit=False)
            former.comment_text = form.cleaned_data['comment_text']
            former.comment_author = request.user
            former.comment_post = thread
            former.save()
            return HttpResponseRedirect(reverse('Board:thread', kwargs={'pk':thread.id}))
        else:
            raise Http404("Something went wrong")

    form = CommentForm()
    context = {
        'thread': thread,
        'form': form,
        'comments': comments
    }
    return HttpResponse(template.render(context, request))

chat/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required()
def index(request):
    return render(request, 'chat/index.html', {})


@login_required()
def room(request, room_name):
    return render(request, 'chat/room.html', {
        'room_name': room_name
    })

auth_/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/master.css' %}" type="text/css">
</head>
<body>
<div class="container">
    <div class="row">
    <div class="col-lg-2 col-xl-2 "></div>
        <div class="col-lg-8 col-xl-8 ">
{% if user.is_authenticated %}
<h1>Welcome to Matrix, {{ user.username }}</h1>
            <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">Logged in as {{ user.username }} </li>
        <li class="breadcrumb-item"><a href="{% url 'Auth_:logout' %}">Logout</a></li>
        <li class="breadcrumb-item"><a href="{% url 'Board:board' %}">Board</a></li>
        <li class="breadcrumb-item"><a href="{% url 'Chat:index' %}">Chat</a></li>
        {% if user.id == 1 %}
        <li class="breadcrumb-item"><a href="admin/">Admin</a></li>
        {% endif %}
  </ol>
</nav>
{% else %}
            <h1>Welcome to Matrix</h1>
            <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'login' %}">Login</a></li>
        <li class="breadcrumb-item"><a href="{% url 'Auth_:register' %}">Register</a></li>
  </ol>
</nav>
{% endif %}

    </div>
    <div class="col-lg-2 col-xl-2 "></div>
</div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
</body>
</html>

board/templates/board/board.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main board</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/master.css' %}" type="text/css">
</head>
<body>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">Logged in as {{ user.username }} </li>
        <li class="breadcrumb-item"><a href="{% url 'Auth_:logout' %}">Logout</a></li>
        <li class="breadcrumb-item"><a href="{% url 'Auth_:index' %}">Home</a> </li>
        <li class="breadcrumb-item"><a href="{% url 'Chat:index' %}">Chat</a></li>
  </ol>
</nav>

<div class="container">
    <div class="row">
        <div class="col-lg-2 col-xl-2 "></div>
        <div class="col-lg-8 col-xl-8 ">
{% if latest_threads %}
    <div>
{% for thread in latest_threads %}
        <div class="card">
            <div class="card-title"><h4><a href="{{ thread.id }}">{{ thread.thread_title }}</a></h4></div>
            <div class="card-text"><h6>Category: {{ thread.category }}</h6></div>
<br />
            <h5>{{ thread.thread_text }}</h5>
        </div>
<br /><br />
{% endfor %}
{% endif %}
    </div>
<form method="post" class="">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" name="thread">POST</button>
</form>
    </div>
        <div class="col-lg-2 col-xl-2 "></div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

board/templates/board/thread.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>This is thread </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
      {% load static %}
    <link rel="stylesheet" href="{% static '/css/master.css' %}" type="text/css">
</head>
<body>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">Logged in as {{ user.username }} </li>
        <li class="breadcrumb-item"><a href="{% url 'Auth_:logout' %}">Logout</a></li>
        <li class="breadcrumb-item"><a href="{% url 'Auth_:index' %}">Home</a> </li>
        <li class="breadcrumb-item"><a href="{% url 'Board:board' %}">Board</a></li>
        <li class="breadcrumb-item"><a href="{% url 'Chat:index' %}">Chat</a></li>
  </ol>
</nav>

<div class="container">
    <div class="row">
            <div class="col-lg-2 col-xl-2 "></div>
            <div class="col-lg-8 col-xl-8 ">
    <div class="card">
        <div class="card-title"><h4> {{ thread.thread_title }} &nbsp;</h4></div>
            <h6>Category: {{ thread.category }}</h6><br />
        <div class="card-text"><h5> {{ thread.thread_text }} </h5>
            {% if thread.thread_author == user.username %}
                <button type="button" class="btn btn-link shadow-none" data-toggle="modal" data-target="#exampleModal">
  Delete
</button>
                <!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content matrixstyle">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Confirm deletion</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete {{ thread.thread_title }}?
      </div>
      <div class="modal-footer">
          <form action="{% url 'Board:delete_thread' thread.id %}" method="POST">
                {% csrf_token %}
        <button type="button" class="btn btn-secondary shadow-none" data-dismiss="modal">No</button>
        <button type="submit" value="Delete" class="btn btn-secondary shadow-none">Yes</button>
      </form>
      </div>
    </div>
  </div>
</div>

<!--                <input type="submit" value="Delete" style="background-color: black; color: green; border: none; text-decoration: underline;">-->
            {% endif %}
    </div>
<hr />

    {% for comment in comments %}
    {{ comment.comment_author }} replied @ {{ comment.pub_date }}<br />
    {{ comment }}<br /><br />
    {% endfor %}
    <form method="post" class="">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn-secondary shadow-none" name="comment">POST</button>
</form>
            </div>
            <div class="col-lg-2 col-xl-2 "></div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</div>
</body>
</html>

chat/templates/chat/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'css/master.css' %}" type="text/css">

</head>
<body>
<div class="container">
    <div class="row">
    <div class="col-lg-2 col-xl-2 "></div>
    <div class="col-lg-8 col-xl-8 ">
    <h1>Welcome to Matrix, {{ user.username }}</h1>
            <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">Logged in as {{ user.username }} </li>
        <li class="breadcrumb-item"><a href="{% url 'Auth_:logout' %}">Logout</a></li>
        <li class="breadcrumb-item"><a href="{% url 'Board:board' %}">Board</a></li>
        <li class="breadcrumb-item"><a href="{% url 'Chat:index' %}">Chat</a></li>
  </ol>
</nav>

    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" placeholder="Enter room name here" style="background-color: black; color: green; border-width: 1px;" width="100%"><br>
    <input id="room-name-submit" type="button" style="background-color: black; color: green; border: none;" value="Enter">
    </div>
    <div class="col-lg-2 col-xl-2 "></div>
</div>
</div>
    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
</body>
</html>

chat/templates/chat/room.html
<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
     {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'css/master.css' %}" type="text/css">
</head>
<body>
<div class="container">
    <textarea disabled id="chat-log" cols="100" rows="20" style="background-color: black; color: green; border: none;"></textarea><br>
    <input id="chat-message-input" type="text" placeholder="Type your message here" style="background-color: black; width: 100%; color: white; height: 2rem" size="100"><br>
<!--    <div class="row">-->
        <input id="chat-message-submit" type="button" style="background-color: black; width: 100%; color: white; height: 2rem" value="Send">
        <a href="{% url 'Chat:index' %}"><input type="button" style="background-color: black; width: 100%; color: white; height: 2rem" value="Exit"></a>
<!--    </div>-->
    {{ room_name|json_script:"room-name" }}
</div>
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message,
            }));
            messageInputDom.value = '';
        };
    </script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

</body>
</html>